name: Python Flask CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify pytest installation
      run: |
        pytest --version

    - name: Run tests
      run: |
        pytest

    - name: Run linting
      run: |
        flake8 .

    - name: Start Flask application
      run: |
        python app.py  # Update this line as needed to start your Flask application


    - name: Start Flask application
      run: |
        python app.py
